### PR TITLE
Feature/kpp export species formula

### PR DESCRIPTION
**Pull request by stulacy**
Addresses #257 by replacing the `IGNORE` species definition in the KPP export by its composition where known from the Inchi.

### CODE REVIEW

**Comment by stulacy** [comment]
I've implemented this feature which produces [this `.eqn` file](https://github.com/wacl-york/mcm-web/files/13951141/isoprene_export_new.txt)  for the usual Isoprene test mechanism.
Does that look as expected @RolfSander ?

**Comment by stulacy** [comment]
The export seems to handle 2-character names OK, here's 'VINCL' from a[kpp_full.txt](https://github.com/wacl-york/mcm-web/files/13953625/kpp_full.txt): 

```
CH2OHCCLO2 = 2C + 4H + Cl + 3O ;
VINCL = 2C + 3H + Cl ;
CH2OHCCLO = 2C + 4H + Cl + 2O ;
```

Did files have a trailing new line previously? From the code I can't see how they ever did. I can add this in no problem however.

I'll check with a colleague about why Inchis aren't available for inorganic species, I'm sure there was a reason...

Yes, the archives will always be kept updated with a copy of the full mechanism in each format we support.

**Comment by RolfSander** [comment]
> The export seems to handle 2-character names OK, here's 'VINCL' from a
> full mechanism:
>
> CH2OHCCLO2 = 2C + 4H + Cl + 3O ;
> VINCL = 2C + 3H + Cl ;
> CH2OHCCLO = 2C + 4H + Cl + 2O ;

Thanks for checking, that's reassuring.

> Did files have a trailing new line previously? From the code I can't
> see how they ever did. I can add this in no problem however.

It's possible that it has always been missing, I don't know. When I was
using files generated by the old MCM web page, I always applied some
postprocessing which added the newline for me. I never checked this
until now.

> I'll check with a colleague about why Inchis aren't available for
> inorganic species, I'm sure there was a reason...

OK, thanks.

> Yes, the archives will always be kept updated with a copy of the full
> mechanism in each format we support.

Great :-)

**Comment by stulacy** [comment]
I've added the inchis (and thus formulae) for the inorganic species that were previously missing, as well as a terminating new-line. Here is the latest 
[isoprene mechanism](https://github.com/wacl-york/mcm-web/files/13990956/isoprene.txt)

The only species without formulae now are the `NA` and `SA` placeholders, as defined [here](https://mcm.york.ac.uk/MCM/inorganic?category=Gas-particle)

If that all looks good to you @RolfSander I can push it live next week.

**Comment by stulacy** [comment]
> 2H + O, not H + 2O

D'oh! It's Friday afternoon and I'm quite unwell. Will correct shortly.

**Comment by RolfSander** [comment]
> I've added the inchis (and thus formulae) for the inorganic species that
> were previously missing, as well as a terminating new-line.

Thanks very much!

> The only species without formulae now are the NA and SA placeholders,
> as defined here

That's fine. As they refer to the condensed phase, they are different
anyway.

One more little bug:

HSO3 = 2H + 3O + S

There should be only 1 H.

> It's Friday afternoon

Have a nice weekend!

**Comment by stulacy** [comment]
Ah I'll need to run the HSO3 issue by a colleague as I was provided the species information by them.
We can catch up next week :)

**Comment by stulacy** [comment]
Hi @RolfSander , I've identified the correct compound with my colleague and have updated the database accordingly (https://github.com/wacl-york/mcm-db/pull/8).
Here's the latest [isoprene mechanism](https://github.com/wacl-york/mcm-web/files/14022243/mcm_export.txt), does it look ready for release now?

**Comment by RolfSander** [comment]
Yes, perfect!

**Pull request merged**
